spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/struts?useSSL=false&useUnicode=true&character_set_server=utf8mb4
    username: root
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp